[options]
addons_path = 
    /home/khetha/projects/subserve-tools/subserve-odoo/addons,
    /home/khetha/projects/subserve-tools/custom-addons,
    /home/khetha/projects/subserve-tools/iot,
    /home/khetha/projects/subserve-tools/OCA_pos

db_host = 127.0.0.1
db_port = 5432
db_user = odoo
db_password = Subserve100
http_port = 8069

logfile = /home/khetha/projects/subserve-tools/subserve-odoo/odoo.log

